### ISSUE TITLE
Get-NexusNuGetApiKey does not work with a user not authenticated through Connect-NexusServer

### ISSUE THREAD

**Issue by JPRuskin** [steviecoaster/NexuShell#7]
This is because it (and the child function for getting a token) use the `$script:Header` containing the auth token for the original user.

I see a few ways to sort this:
- Replace the use of `$Header` within the two functions with a base authentication token generated from the passed Credential
- Require that folk run `Connect-NexusServer` before using it

I feel the former feels better. I'll happily submit a PR shortly, if that seems reasonable.

**Comment by steviecoaster** [comment]
Aye. That's a smart change. I'll implement the new header as the fix.
